const data = {
    "count": 43725,
    "page": 1,
    "page_count": 100,
    "page_size": 100,
    "products": [
        // Maillots //
        {
            "code": "11",
            "product_name": "Maillot de Lubsilubs",
            "category": "maillot",
            "image_avant": "./image/maillotlubsilubsavant.png",
            "image_arriere": "./image/maillotlubsilubsarriere.png",
            "price" : "69,99€",
        },
        {
            "code": "12",
            "product_name": "Maillot de Greg",
            "category": "maillot",
            "image_avant": "./image/maillotgregavant.png",
            "image_arriere": "./image/maillotgregarriere.png",
            "price" : "69,99€",
        },
        {
            "code": "13",
            "product_name": "Maillot de Titou",
            "category": "maillot",
            "image_avant": "./image/maillottitouavant.png",
            "image_arriere": "./image/maillottitouarriere.png",
            "price" : "69,99€",
        },
        {
            "code": "14",
            "product_name": "Maillot de Adrilux",
            "category": "maillot",
            "image_avant": "./image/maillotadriluxavant.png",
            "image_arriere": "./image/maillotadriluxarriere.png",
            "price" : "69,99€",
        },
        // Sweat sans capuche //
        {
            "code": "21",
            "product_name": "Sweat sans capuche de Lubsilubs",
            "category": "sweat-sans-capuche",
            "image_avant": "./image/sweatlubsilubsavant.png",
            "image_arriere": "./image/sweatlubsilubsarriere.png",
            "price" : "59,98€",
        },
        {
            "code": "22",
            "product_name": "Sweat sans capuche de Greg",
            "category": "sweat-sans-capuche",
            "image_avant": "./image/sweatgregavant.png",
            "image_arriere": "./image/sweatgregarriere.png",
            "price" : "59,98€",
        },
        {
            "code": "23",
            "product_name": "Sweat sans capuche de Titou",
            "category": "sweat-sans-capuche",
            "image_avant": "./image/sweattitouavant.png",
            "image_arriere": "./image/sweattitouarriere.png",
            "price" : "59,98€",
        },
        {
            "code": "24",
            "product_name": "Sweat sans capuche de Adrilux",
            "category": "sweat-sans-capuche",
            "image_avant": "./image/sweatadriluxavant.png",
            "image_arriere": "./image/sweatadriluxarriere.png",
            "price" : "59,98€",
        },
        {
            "code": "25",
            "product_name": "Sweat sans capuche équipe",
            "category": "sweat-sans-capuche",
            "image_avant": "./image/sweatlogoavant.png",
            "image_arriere": "./image/sweatlogoarriere.png",
            "price" : "59,98€",
        },
        // Sweat à capuche //
        {
            "code": "31",
            "product_name": "Sweat à capuche de Lubsilubs",
            "category": "sweat-capuche",
            "image_avant": "./image/sweatlubsilubs!.png",
            "image_arriere": "./image/sweatlubsilubsarriere!.png",
            "price" : "64,97€",
        
        },
        {
            "code": "32",
            "product_name": "Sweat à capuche de Greg",
            "category": "sweat-capuche",
            "image_avant": "./image/sweatgreg!.png",
            "image_arriere": "./image/sweatgregarriere!.png",
            "price" : "64,97€",
        },
        {
            "code": "33",
            "product_name": "Sweat à capuche de Titou",
            "category": "sweat-capuche",
            "image_avant": "./image/sweattitou!.png",
            "image_arriere": "./image/sweattitouarriere!.png",
            "price" : "64,97€",
        },
        {
            "code": "34",
            "product_name": "Sweat à capuche de Adrilux",
            "category": "sweat-capuche",
            "image_avant": "./image/sweatadrilux!.png",
            "image_arriere": "./image/sweatadriluxarriere!.png",
            "price" : "64,97€",
        },
        {
            "code": "35",
            "product_name": "Sweat à capuche équipe",
            "category": "sweat-capuche",
            "image_avant": "./image/sweatequipe!.png",
            "image_arriere": "./image/sweatequipearriere!.png",
            "price" : "64,97€",
        },
        // accessoires //
        {
            "code": "41",
            "product_name": "Casquette",
            "category": "accessoire",
            "image_avant": "./image/casquette.png",
            "image_arriere": "./image/casquette.png",
            "price" : "19,99€",
        },
        {
            "code": "42",
            "product_name": "Tablier",
            "category": "accessoire",
            "image_avant": "./image/tablier.png",
            "image_arriere": "./image/tablier.png",
            "price" : "34,99€",
        },
        {
            "code": "43",
            "product_name": "Tote Bag",
            "category": "accessoire",
            "image_avant": "./image/totebag.png",
            "image_arriere": "./image/totebag.png",
            "price" : "34,99€",
        },
        {
            "code": "44",
            "product_name": "Coussin",
            "category": "accessoire",
            "image_avant": "./image/coussin.png",
            "image_arriere": "./image/coussin.png",
            "price" : "29,99€",
        },
        // accessoire bebe //
        {
            "code": "51",
            "product_name": "Bavoir pour bébé",
            "category": "accessoire-bebe",
            "image_avant": "./image/bavoirequipe.png",
            "image_arriere": "./image/bavoirequipe.png",
            "price" : "32,62€",
        },
        {
            "code": "52",
            "product_name": "Bavoir pour bébé Lubsilubs",
            "category": "accessoire-bebe",
            "image_avant": "./image/bavoirlubsilubs.png",
            "image_arriere": "./image/bavoirlubsilubs.png",
            "price" : "32,62€",
        },
        {
            "code": "53",
            "product_name": "Bavoir pour bébé Adrilux",
            "category": "accessoire-bebe",
            "image_avant": "./image/bavoiradrilux.png",
            "image_arriere": "./image/bavoiradrilux.png",
            "price" : "32,62€",
        },
        {
            "code": "54",
            "product_name": "Bavoir pour bébé Titou",
            "category": "accessoire-bebe",
            "image_avant": "./image/bavoirtitou.png",
            "image_arriere": "./image/bavoirtitou.png",
            "price" : "32,62€",
        },
        {
            "code": "55",
            "product_name": "Bavoir pour bébé Greg",
            "category": "accessoire-bebe",
            "image_avant": "./image/bavoirgreg.png",
            "image_arriere": "./image/bavoirgreg.png",
            "price" : "32,62€",
        },
        {
            "code": "56",
            "product_name": "Bavoir pour bébé Titou",
            "category": "accessoire-bebe",
            "image_avant": "./image/bodytitouavant.png",
            "image_arriere": "./image/bodytitou.png",
            "price" : "32,62€",
        },
        {
            "code": "57",
            "product_name": "Bavoir pour bébé Adrilux",
            "category": "accessoire-bebe",
            "image_avant": "./image/bodyadriluxavant.png",
            "image_arriere": "./image/bodyadrilux.png",
            "price" : "32,62€",
        },
        {
            "code": "58",
            "product_name": "Bavoir pour bébé Lubsilubs",
            "category": "accessoire-bebe",
            "image_avant": "./image/bodylubsilubsavant.png",
            "image_arriere": "./image/bodylubsilubs.png",
            "price" : "32,62€",
        },
        {
            "code": "59",
            "product_name": "Body pour bébé Greg",
            "category": "accessoire-bebe",
            "image_avant": "./image/bodygregavant.png",
            "image_arriere": "./image/bodygreg.png",
            "price" : "32,62€",
        },
        {
            "code": "50",
            "product_name": "Body pour bébé",
            "category": "accessoire-bebe",
            "image_avant": "./image/body.png",
            "image_arriere": "./image/body.png",
            "price" : "36,75€",
        },
        // t-shirt //

        {
            "code": "61",
            "product_name": "Polo",
            "category": "t-shirt",
            "image_avant": "./image/polo.png",
            "image_arriere": "./image/polo!.png",
            "price" : "41,76€",
        }, 
        {
            "code": "62",
            "product_name": "T-shirt classique",
            "category": "t-shirt",
            "image_avant": "./image/t-shirt.png",
            "image_arriere": "./image/tshirtdos0.png",
            "price" : "25,48€",
        }, 
        {
            "code": "63",
            "product_name": "T-shirt, Big Neuils dans le dos",
            "category": "t-shirt",
            "image_avant": "./image/t-shirt.png",
            "image_arriere": "./image/t-shirtdos1.png",
            "price" : "25,48€",
        }, 
        {
            "code": "64",
            "product_name": "T-shirt, 4 Big Neuils dans le dos",
            "category": "t-shirt",
            "image_avant": "./image/t-shirt.png",
            "image_arriere": "./image/t-shirtdos2.png",
            "price" : "25,48€",
        }, 
        {
            "code": "65",
            "product_name": "T-shirt avec les joueurs sur le dos",
            "category": "t-shirt",
            "image_avant": "./image/t-shirt.png",
            "image_arriere": "./image/t-shirtdos3.png",
            "price" : "25,48€",
        }, 
        {
            "code": "66",
            "product_name": "T-shirt, je suis fans des Big Neuils",
            "category": "t-shirt",
            "image_avant": "./image/t-shirt.png",
            "image_arriere": "./image/tshirtdos4.png",
            "price" : "25,48€",
        }, 
        {
            "code": "67",
            "product_name": "T-shirt, Champions Grisolles 2023-2024",
            "category": "t-shirt",
            "image_avant": "./image/tshirt1.png",
            "image_arriere": "./image/tshirtdos5.png",
            "price" : "25,48€",
        }, 


    ]
}
